options:
  arena:
    name: "West"
    needed-players: 2
    locations:
      lobby-location:
        world: "A-World"
        x: 1
        y: 2
        z: 3
      game-location:
        world: "A-World"
        x: 1
        y: 2
        z: 3


